---
# mqtt:
sensor:
  - name: "utility_power"
    state_topic: "event/metering/summation/minute"
    unit_of_measurement: 'W'
    icon: mdi:transmission-tower
    value_template: "{{ value_json.value | round (3) }}"
		
  - name: "Garage Motion Sensor"
    state_topic: "stat/garage_motion_sensor/PIR1"
    availability_topic: "tele/garage_motion_sensor/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
  - name: "Instant Energy Use"
    state_topic: "event/metering/instantaneous_demand"
    unit_of_measurement: "W"
    value_template: "{{ value_json.demand | int }}"

  - name: "Outside Temperature"
    state_topic: "sensor/temperature/outside"
    unit_of_measurement: "°F"

  - name: "Inside Temperature"
    state_topic: "sensor/temperature/inside"
    unit_of_measurement: "°F"
  - name: "Front Door Motion Attributes"
    state_topic: "ring/bff646f4-52d5-423d-941e-2d5a21397ea5/camera/247d4dc344b6/motion/attributes"
    value_template: "{{ value_json }}"
    json_attributes_topic: "ring/bff646f4-52d5-423d-941e-2d5a21397ea5/camera/247d4dc344b6/motion/attributes"

light:
  - name: "Kitchen Light"
    state_topic: "stat/kitchen_light/POWER1"
    command_topic: "cmnd/kitchen_light/EVENT"
    availability_topic: "tele/kitchen_light/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Garage Lights"
    state_topic: "stat/SW_Garage_Lights/POWER1"
    command_topic: "cmnd/SW_Garage_Lights/EVENT"
    availability_topic: "tele/SW_Garage_Lights/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "TV Light"
    state_topic: "stat/light_tv/POWER1"
    command_topic: "cmnd/light_tv/EVENT"
    availability_topic: "tele/light_tv/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Couch Light"
    state_topic: "stat/light_couch/POWER1"
    command_topic: "cmnd/light_couch/EVENT"
    availability_topic: "tele/light_couch/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Front Porch Light"
    state_topic: "stat/light_Front_Porch/POWER1"
    command_topic: "cmnd/light_Front_Porch/EVENT"
    availability_topic: "tele/light_Front_Porch/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Living Room Lights"
    state_topic: "stat/SW_Living_Room/POWER1"
    command_topic: "cmnd/SW_Living_Room/EVENT"
    availability_topic: "tele/SW_Living_Room/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"

  - name: "Hallway Lights"
    state_topic: "stat/SW_Hallway/POWER1"
    command_topic: "cmnd/SW_Hallway/EVENT"
    availability_topic: "tele/SW_Hallway/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    
binary_sensor:
  - name: "Front Door Motion"
    state_topic: "ring/bff646f4-52d5-423d-941e-2d5a21397ea5/camera/247d4dc344b6/motion/state"
    payload_on: "ON"
    payload_off: "OFF"
